# Docker compose YAML file to start an elk container
elk:
  image: sebp/elk:latest
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    # mount the sameer project's elk dir as /data on the container
    # format LOCAL:CONTAINER, so change LOCAL, leave :/data
    - ~/sameer/projects/data/elk:/data

